version: '3'

services:

  autos:
    build:
      context: ./services/autos
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@autos-db:5432/autos_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@autos-db:5432/autos_test
    depends_on:
      - autos-db

  autos-db:
    build:
      context: ./services/autos/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - autos